language: node_js # 设置语言

node_js: stable # 设置相应的版本

# S: Build Lifecycle
install:
  - npm install # 安装hexo及插件

# before_script:
#   - npm install -g gulp

script:
  # - git clone https://github.com/Lemonreds/hexo-theme-Nayo themes/nayo
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - ls -al themes/next
  - git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
  - ls -al themes/next/source/lib
  - sed -i 's|theme:\ vno|theme:\ next|g' _config.yml
  - sed -i 's|badges:\ false|badges:\ true|g' themes/next/_config.yml
  - sed -i 's|reading_progress:\n\  enable:\ false|reading_progress:\n\  enable:\ true|g' themes/next/_config.yml
  - cat themes/next/_config.yml
  - hexo clean # 清除
  - hexo generate # 生成静态网页

after_script:
  - cd public
  - git init
  - git config user.name "opsforce" # 修改name
  - git config user.email "i@opsforce.org" # 修改email
  - git add .
  - git commit -m "update site" # 此处看情况修改
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages # GH_TOKEN是在Travis中配置token的名称
# E: Build LifeCycle

branches:
  only:
    - master # 只监测master分支，对应的源码分支

env:
  global:
    - GH_REF: github.com/opsforce/site.git # 设置GH_REF，注意更改