name: github pages generate and deploy

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Handle somethings before building
        run: |
          # - git clone https://github.com/Lemonreds/hexo-theme-Nayo themes/nayo
          git clone https://github.com/theme-next/hexo-theme-next themes/next
          ls -al themes/next
          git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
          ls -al themes/next/source/lib

          sed -i 's|theme:\ vno|theme:\ next|g' _config.yml

          # theme_config=themes/next/_config.yml

          # 设置 theme next 的样式
          sed -i 's|scheme: Muse|# scheme: Muse|' themes/next/_config.yml
          sed -i 's|#scheme: Mist|scheme: Mist|' themes/next/_config.yml
          sed -i -e 's|darkmode: .*|darkmode: true|' themes/next/_config.yml

          # 设置边栏
          sed -i 's|  position: left|  # position: left|' themes/next/_config.yml
          sed -i 's|  #position: right|  position: right|' themes/next/_config.yml

          # 禁用 menu_settings icon
          sed -i 's|  icons: true|  icons: false|' themes/next/_config.yml
          sed -i 's|badges:\ false|badges:\ true|g' themes/next/_config.yml

          # 添加 豆瓣电影 菜单
          sed -i '/fa-archive/a\\  Movies: \/movies\/ \|\| fa fa-movies' themes/next/_config.yml
          sed -i 's|  home: \/|  # home: \/|' themes/next/_config.yml
          sed -i 's|  #about|  about|' themes/next/_config.yml
          sed -i 's|  #categories|  categories|' themes/next/_config.yml
          sed -i 's|  #tags|  tags|' themes/next/_config.yml

          # 开启阅读进程
          sed -i ':a;N;$!ba;s#reading_progress:\n  enable: false#reading_progress:\n  enable: true#' themes/next/_config.yml

          # 开启本地搜索
          # sed -i ':a;N;$!ba;s#local_search:\n  enable: false#local_search:\n  enable: true#' themes/next/_config.yml

          # 集成 algolia 搜索
          sed -i ':a;N;$!ba;s#algolia_search:\n  enable: false#algolia_search:\n  enable: true#' themes/next/_config.yml
          sed -i "s|ALGOLIA_APPLICATION_ID|${{ secrets.ALGOLIA_APPLICATION_ID }}|" _config.yml
          sed -i "s|ALGOLIA_SEARCH_ONLY_API_KEY|${{ secrets.ALGOLIA_SEARCH_ONLY_API_KEY }}|" _config.yml

          # 打印站点配置文件
          echo '################################ 站点配置文件 START ################################'
          cat _config.yml
          echo '################################ 站点配置文件 END ################################'

          # 打印 theme next 配置文件
          echo '################################ theme next 配置文件 START ################################'
          cat themes/next/_config.yml
          echo '################################ theme next 配置文件 END ################################'

      - name: Build
        run: |
          export HEXO_ALGOLIA_INDEXING_KEY=${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: main  # deploying branch
