name: github pages generate and deploy

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Handle somethings before building
        run: |
          # - git clone https://github.com/Lemonreds/hexo-theme-Nayo themes/nayo
          git clone https://github.com/theme-next/hexo-theme-next themes/next
          ls -al themes/next
          git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
          ls -al themes/next/source/lib
          sed -i 's|theme:\ vno|theme:\ next|g' _config.yml
          sed -i 's|badges:\ false|badges:\ true|g' themes/next/_config.yml
          sed -i 's|reading_progress:\n\ \ enable:\ false|reading_progress:\n\ \ enable:\ true|g' themes/next/_config.yml
          cat themes/next/_config.yml

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: main  # deploying branch
